VAGRANTFILE_API_VERSION = "2"  

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|                          
                                                                                
  # Every Vagrant virtual environment requires a box to build off of.           
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  
  config.vm.network "forwarded_port", guest: 2375, host: 2376, auto_correct: true
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "dockerhostvm"
  end

  config.vm.synced_folder "../data", "/vagrant_data"   
  config.vm.provision "shell", path: "../bootstrap.sh", args: ['--proxyUser', ENV['PROXY_USER'], '--proxyPass', ENV['PROXY_PASS'], '--proxyHost', ENV['PROXY_HOST'], '--proxyPort', ENV['PROXY_PORT']]   
end
