# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"  

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.network "forwarded_port", guest: 2375, host: 2376, auto_correct: true
  # google cadvisor
  config.vm.network "forwarded_port", guest: 8080, host: 4010, auto_correct: true
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
 vb.name = "dockervm"
  end

  config.vm.synced_folder "../data", "/vagrant_data"   
  config.vm.provision "shell", path: "../bootstrap.sh", args: ['--proxyUser', ENV['PROXY_USER'], '--proxyPass', ENV['PROXY_PASS'], '--proxyHost', ENV['PROXY_HOST'], '--proxyPort', ENV['PROXY_PORT']]   
end
